### ISSUE TITLE
Filterbar模拟器下，过滤条件画面切换radiobutton的选项的时候出item.children.map is not a function 错误，但是真机下可以

### ISSUE THREAD

**Issue by guofengma** [skyvow/wux#45]
thirdScriptError
item.children.map is not a function;at pages/searchres/searchres page $wux.filterbar.onRadioChange function
TypeError: item.children.map is not a function
    at Component.onRadioChange (http://778647474.appservice.open.weixin.qq.com/components/filterbar/filterbar.js:96:40)
    at e.a (http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:9:1781)
    at N (http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:8:29135)
    at Function.<anonymous> (http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:8:30690)
    at http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:9:3284
    at http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:4:5247
    at e.(anonymous function) (http://778647474.appservice.open.weixin.qq.com/__dev__/WAService.js:4:18529)
    at d (http://778647474.appservice.open.weixin.qq.com/appservice:16:7288)
    at g.registerCallback (http://778647474.appservice.open.weixin.qq.com/appservice:16:7468)
    at k.forEach (http://778647474.appservice.open.weixin.qq.com/appservice:16:3140)

**Comment by guofengma** [comment]
微信开发工具v1.01.170913, 基础库版本1.5.3,

**Comment by skyvow** [comment]
@guofengma 检查一下传入数据 children 不是数组类型
